### PR TITLE
Move jasmine types to devDependencies

### LINKED ISSUE #37: Please move @types/jasmine to devDependencies
Please move `@types/jasmine` to devDependencies, as it is needed for testing only.

It clashes with the `@types/mocha` in my project, as both of them use the same global identifier:

```
../../node_modules/@types/jasmine/index.d.ts(14,18): error TS2300: Duplicate identifier 'describe'.
../../node_modules/@types/jasmine/index.d.ts(16,18): error TS2300: Duplicate identifier 'xdescribe'.
../../node_modules/@types/jasmine/index.d.ts(25,18): error TS2300: Duplicate identifier 'it'.
../../node_modules/@types/jasmine/index.d.ts(35,18): error TS2300: Duplicate identifier 'xit'.
../../node_modules/@types/mocha/index.d.ts(36,13): error TS2300: Duplicate identifier 'describe'.
../../node_modules/@types/mocha/index.d.ts(37,13): error TS2300: Duplicate identifier 'xdescribe'.
../../node_modules/@types/mocha/index.d.ts(42,13): error TS2300: Duplicate identifier 'it'.
../../node_modules/@types/mocha/index.d.ts(43,13): error TS2300: Duplicate identifier 'xit'.
```

### PR DESCRIPTION
**Pull request by juriwiens**
Fixes #37 

I wanted to run the tests before and after my changes, but they failed as described in #39

### CODE REVIEW

**Comment by juriwiens** [comment]
Already fixed by PR #38
